### ISSUE TITLE
Still seeing JS errors in the action execution

### ISSUE THREAD

**Issue by simoneb** [nearform/optic-release-automation-action#185]
This execution happened after the latest release, and there are still JS errors.

https://github.com/nearform/mercurius-explain-graphiql-plugin/actions/runs/3532892640

**Comment by simoneb** [comment]
@sameer-coder can you please look into this?

**Comment by sameer-coder** [comment]
The release of the action did not happen due to some GitHub issue. I have done a proper release now. I will wait to see if the error happens again.

**Comment by sameer-coder** [comment]
Closing this issue since release notes generation is handled by GitHub automatically.
