### ISSUE TITLE
If the release is a prerelease treat it as a prerelease using the Update Release API

### ISSUE THREAD

**Issue by davideroffo** [nearform/optic-release-automation-action#218]
If we want to treat a release as a prerelease GitHub provides the user with the ability of setting it directly with the [Update Release API](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#update-a-release).

We want to add this feature in order to treat the prereleases as prereleases and not as releases (as we currently do).

In order to do that we need to call the `optic-release-automation-app` with a new parameter `isPreRelease` and update accordingly the app source code to handle this new parameter https://github.com/nearform/optic-release-automation-app/issues/196 .

**Comment by simoneb** [comment]
Let's do this now so we include this when we release the prerelease support, as it's a nice to have thing along with that feature
