### ISSUE TITLE
Release branch should be deleted when the PR is closed (without merging)

### ISSUE THREAD

**Issue by simoneb** [nearform/optic-release-automation-action#23]
If the branch is not deleted, the next trigger of the action will error as it will try to recreate the branch

**Comment by ja-bravo** [comment]
Assigning this one to myself @ja-bravo

**Comment by simoneb** [comment]
this is a repo in the org, you can really assign it to yourself without using the convention :)

**Comment by ja-bravo** [comment]
I might be missing something but I don't have the usual "assign to yourself" button on this repo 😅  @simoneb

**Comment by simoneb** [comment]
try again now
