### ISSUE TITLE
Action consistently fails to execute

### ISSUE THREAD

**Issue by matijagaspar** [nearform/optic-release-automation-action#248]
The action always fails with: `Error: Unable to publish to npm: The process '/usr/local/bin/npm' failed with exit code 1`

**Comment by matijagaspar** [comment]
Some explanation regarding the issue:

Before introduction of github `@actions/exec`  (#211) external commands were being executed using node spawn wrapped into a utility function that resolves or rejects using event listeners to collect output and return codes. If error code was not 0 it would reject the promise. Handling of the promise rejection was done in `publishToNpm`.


Using `@action/exec` was done in a similar manner, however `exec` is already an async function that already rejects the promise (hence throws an error if awaited) if the execution returns non 0 return code. However the rejection object does not contain stderr output. The function `execWithOutput` collects and combines the output after the call to exec, so the issue was that the `execWithOutput` did not finish executing, and just rejected with the default `exec` error code (missing the needed stderr output).

The fix was to wrap the `exec` into a try catch, so we can finish processing preparing the stderr and stdout output and construct the error object such that `publishToNpm` can handle it correctly.

**Comment by simoneb** [comment]
great troubleshooting and reporting @matijagaspar , thanks a lot
