### ISSUE TITLE
Document how to use the playground repository for testing

### ISSUE THREAD

**Issue by simoneb** [nearform/optic-release-automation-action#253]
Because we have recently inadvertently introduced multiple issues due to insufficient testing, and because setting up a repo for testing this action is some work, unless you know exactly how to do it, we have created a playground repo sitting at https://github.com/nearform/optic-release-automation-playground.

The idea is to use that repo as a shared playground for anybody in the org to test out their changes. Hence, we need to document how to use it by:

1. introducing a reference to that repo in the readme of this action
2. updating the readme of that repo to explain what needs to be done to use it, which at a high level consists of:
  - sending a PR to use the branch of the action you're working on
  - asking to be added as a maintainer of the npm package so you can publish it
  - generate and populate secrets for npm and optic
  - (probably more I'm forgetting at the moment)

**Comment by p16** [comment]
@simoneb I do not know if it is a problem, but the playground is a private repo, do we need to make it public?

**Comment by simoneb** [comment]
not technically a problem, just let's say unusual to have a public package with a non private repo, but it shouldn't be a blocker for anything
