### ISSUE TITLE
Force tag update

### ISSUE THREAD

**Issue by Eomm** [nearform/optic-release-automation-action#35]
When a new version is released, for example the `v3.0.4`, and the `sync-semver-tags` option is set to true, the existing tags:

- `v3.0`
- `v3`

Should be updated accordingly.

I think here:

https://github.com/nearform/optic-release-automation-action/blob/9058fc8d31698770e4c6e671d1ab52783be0dcf3/utils/tagVersion.js#L9

we are missing a `--force` flag

**Comment by ja-bravo** [comment]
It looks like it's updating the v3 tag for me, I don't think we need the ```--force``` flag as the lines before removes the tag from the remote and force updates the local one before pushing. 

https://github.com/nearform/optic-release-automation-action/blob/9058fc8d31698770e4c6e671d1ab52783be0dcf3/utils/tagVersion.js#L7-L8

See the v6 and v6.0.1 tag matching and all the v5.x.x tags matching in the following screenshot
<img width="450" alt="Screenshot 2021-12-13 at 16 15 11" src="https://user-images.githubusercontent.com/9266627/145839269-8182b6c6-e955-47c6-b8ee-f9e88a3e5e45.png">

Maybe I'm missing something?

It does not create a vX.0 though, should be easy to implement if needed tho

**Comment by simoneb** [comment]
Is this valid? If so, we need to fix it before we can use this to publish actions, meaning that even if we merge #30 , we can't release until this is solved

**Comment by Eomm** [comment]
I have tried the commands and it works. I was not aware that the command `git push origin :refs/tags/v0.5.0` deletes the tag.

```
➜  node-workshop-micro git:(master) ✗ git push origin :refs/tags/v0.5.0
To https://github.com/Eomm/node-workshop-micro.git
 - [deleted]         v0.5.0
➜  node-workshop-micro git:(master) ✗ git tag -f v0.5.0                
Updated tag 'v0.5.0' (was 60e6a10)
➜  node-workshop-micro git:(master) ✗ git push origin --tags           
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/Eomm/node-workshop-micro.git
 * [new tag]         v0.5.0 -> v0.5.0
```

Closing!
