### ISSUE TITLE
Use consistent node version

### ISSUE THREAD

**Issue by simoneb** [nearform/optic-release-automation-action#44]
Let's use a consistent node version throughout the codebase. Let's use nvmrc as the source of truth and Node 16 everywhere

**Comment by ja-bravo** [comment]
I think we're forced to use Node 12 as long as we're using `actions/github-script@v5` because that's what they're using to run our code.

https://github.com/actions/github-script/blob/0c6f00768732ed1187947a986d58800c44dfed88/action.yml#L29-L31

**Comment by simoneb** [comment]
yeah we need to find a compromise here, because while what you say is true, it's also true that remembering to switch to node 12 when working on this repo is hard too, now that we're used to working with node 16. in any case, if we want to stick to node 12 let's address this issue by making sure that nvmrc is the source of truth
