### ISSUE TITLE
Delete branch on success

### ISSUE THREAD

**Issue by Eomm** [nearform/optic-release-automation-action#79]
Right now the `release/` branch deletion is performed only when the OPTIC's PR is not merged:

https://github.com/nearform/optic-release-automation-action/blob/a207fd4013fa12996d492cb9809e4e3411a2eddf/src/release.js#L42

Why this setting?
I think it should be good to delete it in every case to clean up the repository's branches.
The GH release is going to track the version using the git tag.

Example:

- branch not deleted after the release: https://github.com/fastify/fastify-accepts/tree/release/v2.2.0
- the tag created by the GH release: https://github.com/fastify/fastify-accepts/tree/v2.2.0

So, I think that keeping the branches nice and clean is good. What do you think?

**Comment by castarco** [comment]
As far as I can see in the commit history, this if condition didn't start handling branch deletions, but releases deletion. So I guess it's an unintended bug that appeared later.
