### ISSUE TITLE
allow releasing "apps"

### ISSUE THREAD

**Issue by simoneb** [nearform/optic-release-automation-action#9]
It would be good to use this to cut a release of a repository that doesn't contain an npm package. 

Basically it boils down to: how do we skip npm publish (hence, optic)? Is it just a matter of setting pacakge.json's `private: true` or do we need a setting in the action to skip it? (or anything else)

**Comment by ja-bravo** [comment]
Looks like if you skip the npm-token input, the action will skip the publishing to NPM and asking optic for the OTP section.
I tested it in a small repo and it worked just like the docs said https://github.com/nearform/optic-release-automation-action#inputs

**Comment by simoneb** [comment]
Yes @salmanm worked on it already I guess. My initial idea was to skip if the package is private, but it's even better if we skip npm publish (hence optic) by simply omitting the npm token input 👍 . If this works already, we can close it

**Comment by simoneb** [comment]
@ja-bravo @salmanm can we close this?

**Comment by ja-bravo** [comment]
I would say yes, the feature already exists if you omit the npm token input
